### ISSUE TITLE
Support Japanese

### ISSUE THREAD

**Issue by viethoangtien** [MyScript/interactive-ink-examples-android#11]
Hi,
Thanks for your library. Yours are so good in English but how to recognize in Japanese. Please help me!

**Comment by myscript-developer** [comment]
Dear viethoangtien,

thank you for contacting us.

Currently, you shall proceed as indicated on our developer forum: https://developer-support.myscript.com/support/discussions/topics/16000027723

Also, in order to get a faster and more accurate answer, we recommend you submit any question you may have on the latter.

Best regards,

Olivier

**Comment by tuananhkidd** [comment]
@myscript-developer 
i download asset for japanest but when i try replace url in gralde : https://s3-us-west-2.amazonaws.com/iink/assets/1.3.0/myscript-iink-recognition-text-ja_JP.zip
it does not working.
i try to download in webbrower ,i receive "access denies"
Please support me . 
Thanks so much

**Comment by MyScriptSupport** [comment]
Dear Tuấn Anh Kidd,

Thank you for contacting us. If you want to donwlonad some language packs, such as japanese, you should go to our developper site [https://developer.myscript.com/support/recognition-assets](https://developer.myscript.com/support/recognition-assets)
Once you are signed in, you will be able to select the 1.3 version and donwload the Japanase language pack.

Best regards,

Gwenaëlle
